config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

  has_and_belongs_to_many :groups
  has_and_belongs_to_many :users

  # attr_accessor :group_ids
  # attr_accessor :user_ids
  #
  # accepts_nested_attributes_for :groups
  # accepts_nested_attributes_for :users

end

app/models/group.rb
class Group < ApplicationRecord

  has_and_belongs_to_many :courses
  has_many                :users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :group
  has_and_belongs_to_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      # params.require(:course).permit!
      params.require(:course).permit(:title, group_ids: [], user_ids: [])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @users = User.where(group_id: params[:id])
    @courses = Course.includes(:groups).where(groups: {id: params[:id]} )
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit!
      # params.require(:group).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @courses = Course.all
    @groups  = Group.all
    @users   = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/courses/_form.haml
= form_for(course) do |f|
  - if course.errors.any?
    #error_explanation
    %h2
      = pluralize(course.errors.count, "error")
    prohibited this course from being saved:
    %ul
      - course.errors.full_messages.each do |message|
        %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    -Group.all.each do |group|
      -#=hidden_field_tag 'course[group_ids][]', nil
      =label_tag group.name, group.name, style:'font-weight:bold'
      =check_box_tag 'course[group_ids][]', group.id, @course.group_ids.include?(group.id), id: group.name
      -User.where(group_id:group.id).each do |user|
        =hidden_field_tag 'course[user_ids][]', nil
        =label_tag user.email, user.email
        =check_box_tag 'course[user_ids][]', user.id, @course.user_ids.include?(user.id), id: user.email

      %br

  .actions
    = f.submit

app/views/courses/edit.haml
%h1 Editing Course
= render 'form', course: @course
= link_to 'Show', @course
|
= link_to 'Back', courses_path

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.haml
%p#notice= notice

%p
  %strong Title:
  = @course.title
  %br

  %strong Groups:
  - @course.groups.each do |group|
    =group.name
  %br

  %strong Users:
  - @course.users.each do |user|
    =user.email


= link_to 'Edit', edit_course_path(@course)
|
= link_to 'Back', courses_path

app/views/groups/_form.haml
= form_for(group) do |f|
  - if group.errors.any?
    #error_explanation
      %h2
        = pluralize(group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name

  .field
    -Course.all.each do |course|
      =hidden_field_tag 'group[course_ids][]', nil
      =label_tag course.title, course.title
      =check_box_tag 'group[course_ids][]', course.id, @group.course_ids.include?(course.id), id: course.title
      -#=check_box_tag :group_ids, group.id, params[:group_ids].try(:include?, group.id)
      %br

  .field


  .actions
    = f.submit

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.haml
%p#notice= notice
%p
%strong
  Name:
  = @group.name

%br

%strong
  Users:
  %ul
    - @users.each do |user|
      %li= user.email

%br

%strong
  Courses appointed:
  -@courses.each do |course|
    %li= course.title

= link_to 'Edit', edit_group_path(@group)
|
= link_to 'Back', groups_path

app/views/home/index.haml
.container

  %h2 Courses list

  %ol
    -@courses.each do |course|
      %li
        = course.title
        = link_to 'Edit', edit_course_path(course)
        = link_to 'Show', course_path(course)
  =link_to 'Add new course', new_course_path
  %hr

  %h2 Groups list

  %ol
    -@groups.each do |group|
      %li
        = group.name
        = link_to 'Edit', edit_group_path(group)
        = link_to 'Show', group_path(group)
  =link_to 'Add new group', new_group_path
  %hr

  %h2 Users list
  %ol
    -@users.each do |user|
      %li
        = user.email
        = link_to 'Edit', edit_user_registration_path(user)
  -#=link_to 'Add new user', new_user_registration_path

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Courses
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p= link_to 'Main page', root_path


    - if current_user
      You are logged as:
      =link_to current_user.email, edit_user_registration_path
      |
      = link_to 'logout', destroy_user_session_path, method: 'delete'

    - else
      = link_to 'login', new_user_session_path
      |
      = link_to 'sign up', new_user_registration_path

    = yield